### ISSUE TITLE
Fix left/right arrow key moving direction

### ISSUE THREAD

**Issue by ahangarha** [dobidi/logseq-bidi#2]
In RTL text, pressing the left/right arrow keys moves the cursor in the opposite direction.

**Comment by hedimdev** [comment]
Thank you for this really essential plugin. Anything you can do to fix the cursor movement or is it an OS problem? I'm using it on Ubuntu and the cursor movement is very confusing, especially since CTRL+Arrow moves in the correct direction.

**Comment by ahangarha** [comment]
I'm happy to get some response here.
I try to fix this issue this week.

**Comment by ahangarha** [comment]
@hedimdev I just released v0.2.0. Please use and confirm the fix.

**Comment by hedimdev** [comment]
> @hedimdev I just released v0.2.0. Please use and confirm the fix.

Looks good. Thanks for the quick response.

**Comment by hedimdev** [comment]
> @hedimdev I just released v0.2.0. Please use and confirm the fix.

There's an edge case:

1. Create two blocks, the first one can be any text but the second block should be RTL.
2. Place the caret at the beginning of the RTL block.
3. Clicking the right arrow moves the caret back to the end of the previous block (that's correct) but clicking the left arrow does the same (incorrect movement) instead of advancing left into the RTL block.

**Comment by ahangarha** [comment]
I tried different scenarios, but not this one.
Thanks for the feedback. Will be fixed ASAP.

**Comment by hedimdev** [comment]
I just realized the same (or actually the opposite) issue exists at the end of a RTL block. If the caret is at the end of the block, clicking the right arrow moves the caret down to the next block instead of going backwards into the RTL text.

**Comment by ahangarha** [comment]
@hedimdev I just released v0.3.0 and fixed the issue.

Please check and confirm the fix.
